
services:
    attribute.controller.admin:
        class: WellCommerce\Bundle\AttributeBundle\Controller\Admin\AttributeController
        arguments: ['@attribute.manager', '@attribute.form_builder.admin', '@attribute.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    attribute_group.controller.admin:
        class: WellCommerce\Bundle\AttributeBundle\Controller\Admin\AttributeGroupController
        arguments: ['@attribute_group.manager', '@attribute_group.form_builder.admin', '@attribute_group.datagrid']
        calls:
            - [setContainer, ['@service_container']]

    attribute_value.controller.admin:
        class: WellCommerce\Bundle\AttributeBundle\Controller\Admin\AttributeValueController
        arguments: ['@attribute_value.manager', '@attribute_value.form_builder.admin', '@attribute_value.datagrid']
        calls:
            - [setContainer, ['@service_container']]
